variables:
  configuration: release
  platform: any cpu
  azure_redis_host:
  azure_redis_password:

phases:
- template: build_template.yml
  parameters:
    name: Linux
    queue: Hosted Ubuntu 1604

- template: build_template.yml
  parameters:
    name: Windows
    queue: Hosted VS2017
    local_redis: false
